"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['owllook_gui/owllook.py']
APP_NAME = 'owllook'
DATA_FILES = ['owllook_gui/resource/images/Icon.icns']
OPTIONS = {
    'emulate_shell_environment': True,
    'iconfile': 'owllook_gui/resource/images/Icon.icns',
    'plist': {
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
        'LSUIElement': True,
        'CFBundleVersion': "0.0.1",
        'CFBundleShortVersionString': "0.0.1"
    },
    'includes': ['aiohttp', 'async_timeout', 'bs4', 'html5lib', 'PyQt5', 'quamash', 'sqlalchemy_aio']
}

setup(
    name=APP_NAME,
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
